CREATE TABLE `pf_grommets` (`id` INT NOT NULL AUTO_INCREMENT , `client_id` INT NOT NULL , `internal_id` VARCHAR(20) NOT NULL , `wll` INT NOT NULL , `wl` DECIMAL(10,1) NOT NULL , `bl` INT NOT NULL , `qty` INT NOT NULL , `dia` INT NOT NULL , `icc_id` INT NULL , `certificate_number` VARCHAR(100) NOT NULL , `certificate_type_id` INT NULL , `tag_marking` VARCHAR(100) NULL , `manufacturer_id` INT NULL , `supplied_date` DATE NOT NULL , `supplied_place` VARCHAR(100) NULL, `date_of_discharged` DATE NULL, `deleted` TINYINT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `pf_shackles` ADD UNIQUE (`client_id`, `internal_id`);
CREATE TABLE `pf_grommets_loadtest` (`id` INT NOT NULL AUTO_INCREMENT , `grommet_id` INT NOT NULL , `test_date` DATE NULL , `tested_by` VARCHAR(100) NULL , `location` VARCHAR(250) NULL , `passed` TINYINT(1) NULL DEFAULT '0' , `remarks` TEXT NULL , `files` TEXT NULL , `deleted` TINYINT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `pf_grommets_inspection` (`id` INT NOT NULL AUTO_INCREMENT , `grommet_id` INT NOT NULL , `inspection_date` DATE NULL , `inspected_by` VARCHAR(100) NULL , `location` VARCHAR(250) NULL , `passed` TINYINT(1) NULL DEFAULT '0' , `remarks` TEXT NULL , `files` TEXT NULL , `deleted` TINYINT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `pf_shackles` (`id` INT NOT NULL AUTO_INCREMENT , `client_id` INT NOT NULL , `internal_id` VARCHAR(20) NOT NULL , `wll` INT NOT NULL , `type_id` int NOT NULL , `qty` INT NOT NULL , `bl` INT NULL , `iw` INT NOT NULL , `pd` INT NOT NULL , `il` INT NOT NULL , `icc_id` INT NULL , `certificate_number` VARCHAR(100) NOT NULL , `certificate_type_id` INT NULL , `tag_marking` VARCHAR(100) NULL , `manufacturer_id` INT NULL , `supplied_date` DATE NOT NULL , `supplied_place` VARCHAR(100) NULL , `date_of_discharged` DATE NULL, `deleted` TINYINT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `pf_shackles` ADD UNIQUE (`client_id`, `internal_id`);
CREATE TABLE `pf_shackles_loadtest` (`id` INT NOT NULL AUTO_INCREMENT , `shackle_id` INT NOT NULL , `test_date` DATE NULL , `tested_by` VARCHAR(100) NULL , `location` VARCHAR(250) NULL , `passed` TINYINT(1) NULL DEFAULT '0' , `remarks` TEXT NULL , `files` TEXT NULL , `deleted` TINYINT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `pf_shackles_inspection` (`id` INT NOT NULL AUTO_INCREMENT , `shackle_id` INT NOT NULL , `inspection_date` DATE NULL , `inspected_by` VARCHAR(100) NULL , `location` VARCHAR(250) NULL , `passed` TINYINT(1) NULL DEFAULT '0' , `remarks` TEXT NULL , `files` TEXT NULL , `deleted` TINYINT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;


CREATE TABLE `pf_misc` (`id` INT NOT NULL AUTO_INCREMENT , `client_id` INT NOT NULL , `internal_id` VARCHAR(20) NOT NULL , `wll` INT NOT NULL , `wl` DECIMAL(10,1) NOT NULL, `type_id` INT NOT NULL , `bl` INT NOT NULL , `qty` INT NOT NULL , `icc_id` INT NULL , `certificate_number` VARCHAR(100) NOT NULL , `certificate_type_id` INT NULL , `tag_marking` VARCHAR(100) NULL , `manufacturer_id` INT NULL , `supplied_date` DATE NOT NULL , `supplied_place` VARCHAR(100) NULL, `date_of_discharged` DATE NULL, `deleted` TINYINT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `pf_misc` ADD UNIQUE (`client_id`, `internal_id`);
CREATE TABLE `pf_misc_loadtest` (`id` INT NOT NULL AUTO_INCREMENT , `misc_id` INT NOT NULL , `test_date` DATE NULL , `tested_by` VARCHAR(100) NULL , `location` VARCHAR(250) NULL , `passed` TINYINT(1) NULL DEFAULT '0' , `remarks` TEXT NULL , `files` TEXT NULL , `deleted` TINYINT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `pf_misc_inspection` (`id` INT NOT NULL AUTO_INCREMENT , `misc_id` INT NOT NULL , `inspection_date` DATE NULL , `inspected_by` VARCHAR(100) NULL , `location` VARCHAR(250) NULL , `passed` TINYINT(1) NULL DEFAULT '0' , `remarks` TEXT NULL , `files` TEXT NULL , `deleted` TINYINT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;


CREATE TABLE `pf_lashing` (`id` INT NOT NULL AUTO_INCREMENT, `client_id` INT NOT NULL , `category_id` INT NOT NULL , `name` VARCHAR(50) NOT NULL , `description` VARCHAR(250) NULL , `qty` INT NOT NULL , `length` INT NULL , `width` INT NULL , `height` INT NULL , `msl` INT NULL , `bl` INT NULL , `supplied_date` DATE NULL , `supplied_place` VARCHAR(50) NULL , `property` ENUM('SAL','Ship') NOT NULL , `remarks` MEDIUMTEXT NULL , `deleted` TINYINT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;
